---
- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Copy Nginx configuration
  copy:
    src: ../deploy/files/nginx.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Start Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes