---
- name: Install Python
  yum:
    name:
      - python{{ python_version }}
      - python{{ python_version }}-devel
      - python{{ python_version }}-pip
    state: present

- name: Create Python virtual environment
  pip:
    name: virtualenv
    state: present

- name: Create application directory
  file:
    path: "{{ app_path }}"
    state: directory
    owner: ec2-user
    group: ec2-user