---
- name: Create PostgreSQL database
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"

- name: Create PostgreSQL user
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  notify: restart postgresql